# Generated by Django 4.2.25 on 2025-11-26 17:34

import api.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Что вас интересует')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'zayavka',
                'verbose_name_plural': 'zayavki',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Что вас интересует?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'kontact zayavki',
                'verbose_name_plural': 'kontact zayavki',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('schedule', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Кontact info',
                'verbose_name_plural': 'kontaktnaya info',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Design')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Фото')),
                ('date', models.CharField(max_length=100, verbose_name='Дата')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('completed', 'Завершённый'), ('canceled', 'Отменённый'), ('past', 'Прошедший')], default='upcoming', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'meropriyatie',
                'verbose_name_plural': 'meropriyatiya',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Будущее'), ('past', 'Прошедшее')], max_length=50)),
            ],
            options={
                'verbose_name': 'meropriyatie',
                'verbose_name_plural': 'meropriyatiye',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='posts/')),
                ('title', models.CharField(max_length=200)),
                ('ckeditor', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услугии',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/', verbose_name='Фото проекта')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'nashi proekti',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('position', models.CharField(max_length=150, verbose_name='Должность / компания')),
                ('description', models.TextField(verbose_name='Отзыв')),
                ('img', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tools/', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Название технологии')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'instrument',
                'verbose_name_plural': 'instrumenti',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Ссылка на соцсеть')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[api.models.validate_resume], verbose_name='Резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.CreateModel(
            name='ViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=20, verbose_name='Уровень')),
                ('work_type', models.CharField(choices=[('office', 'Полный рабочий день'), ('remote', 'Удаленно'), ('hybrid', 'Гибридный график')], max_length=20, verbose_name='График работы')),
            ],
        ),
    ]
